### ISSUE TITLE
Convert smoke tests to rspec

### ISSUE THREAD

**Issue by derekprior** [thoughtbot/scenic#114]
The tests in `spec/smoke` are difficult for me to work with and I'm familiar with them. I think we'll get better acceptance test coverage and encourage more people to get involved in the project if we move these to Ruby code.

We can still have these run as a separate suite so we have our fast tests and our acceptance tests, which all run on a full `rake`. See the Clearance test suite for an example.

**Comment by devonestes** [comment]
Think since there is so much in that `spec/smoke` file that it would make sense to chip away at it versus having one huge PR? I'd be happy to take a swing at this in the coming days, but I think one huge PR might take a good amount of time.

I totally agree, though, that the `smoke` file is a little gnarly as a newcomer to contributing to the project. However, I did learn a lot of good bash scripting tricks from looking at it, so that's a plus!

**Comment by derekprior** [comment]
I have a branch with these converted. I want to add some rspec matchers to make the error messages friendly. It's not a super high priority right now.

**Comment by derekprior** [comment]
Closing in favor of PR
