### ISSUE TITLE
Issue with inconsistent singularization with materialization

### ISSUE THREAD

**Issue by sirwolfgang** [thoughtbot/scenic#148]
If the generator is using singularization it forgets to do so on the materialization insert.

```ruby
rails generate scenic:model inventory_types --materialized
[WARNING] The model name 'inventory_types' was recognized as a plural, using the singular 'inventory_type' instead. Override with --force-plural or setup custom inflection rules for this noun before running the generator.
      invoke  active_record
      create    app/models/inventory_type.rb
      invoke    rspec
      create      spec/models/inventory_type_spec.rb
      invoke      factory_girl
      create        spec/factories/inventory_types.rb
      insert  app/models/inventory_types.rb
/Users/sirwolfgang/.gem/ruby/2.3.0/gems/thor-0.19.1/lib/thor/actions/inject_into_file.rb:98:in `binread': No such file or directory @ rb_sysopen - /Users/sirwolfgang/Projects/eve/app/models/inventory_types.rb (Errno::ENOENT)```

**Comment by devonestes** [comment]
Looks like there's a warning there - have you tried running this generator with the singular (`inventory_type`), or using the override `--force-plural`?

**Comment by sirwolfgang** [comment]
The warning is expected behavior. It takes the plural, and makes its singular for all of the actions but the last one.

**Comment by calebthompson** [comment]
You may actually have found a bug in Rails, which doesn't singluarize `file_name` in [`assign_names`](https://github.com/rails/rails/blob/master/railties/lib/rails/generators/named_base.rb#L180), but uses the `file_name` as a soft-alias for [`singular_name`](https://github.com/rails/rails/blob/master/railties/lib/rails/generators/named_base.rb#L36) later.

Feel free to PR that if you like, or I can get to it later. In the mean time, I'll call `singularize` where we use the name so our code works and the issue is resolved.
