### ISSUE TITLE
Refresh only part of a materialized view?

### ISSUE THREAD

**Issue by chrismanderson** [thoughtbot/scenic#163]
Say I have a materialized view which has a date field. Is there any way to refresh a materialized view, but ignore anything prior to a certain date? The idea is that, say for an orders view which contains joined data, eventually the orders become fixed and don't need updating anymore.

**Comment by calebthompson** [comment]
This is more of a SQL/Postgres question than a Scenic question.

That said, Postgres does not have facility to refresh a part of a materialized view. You could accomplish this by composing materialized views, some of which don't change, and only refreshing the most recent one and UNION-ing in the previous ones:

```sql
SELECT ...
UNION
SELECT * FROM older_materialized_view_2015
UNION
SELECT * FROM older_materialized_view_2014
```

Or by using an actual table to store results instead of a materialized view

```sql
UPDATE view
...
WHERE date < ...
```

**Comment by chrismanderson** [comment]
Doing the union is a great suggestion. Thanks for the feedback.
