### ISSUE TITLE
Changing column types fails

### ISSUE THREAD

**Issue by leweafan** [thoughtbot/scenic#166]
When I'm trying to change column type I'm getting an error "cannot alter type of a column used by a view or rule". Is there a work around? Can I rollback all views before changing and get it back after?

**Comment by calebthompson** [comment]
Yeah you should be able to drop the view(s) that cause that issue, change the column, and re-add the views (use version specifier).

On Tue, Aug 23, 2016 at 3:35 AM leweafan

<
mailto:leweafan <notifications@github.com>
> wrote:

a, pre, code, a:link, body { word-wrap: break-word !important; }

When I'm trying to change column type I'm getting an error "cannot alter type of a column used by a view or rule". Is there a work around? Can I rollback all views before changing and get it back after?

—

You are receiving this because you are subscribed to this thread.

Reply to this email directly,
https://github.com/thoughtbot/scenic/issues/166
, or

**Comment by leweafan** [comment]
Can I drop all views and get them back using command line?
From gem description I see that if I want to drop views I should create a migration using drop_view.
And it's not clear how I'll get my views back.

**Comment by derekprior** [comment]
This error is from postgres because postgres does not allow you to change the type of a column in a database view. Presumably, you are getting this error because you have a migration such as this (changing `users.bio` from `string` to `text` or something similar):

```ruby
change_column :users, :bio, :text
```

When you run this migration, you will get an error because you have an existing view that uses this column. Let's say that view name was `awesome_users`. To fix, you would update your migration like so:

```ruby
drop_view :awesome_users
change_column :users, :bio, :text
create_view :awesome_users, version: whatever_the_version_number_you_last_used_was
```

If you re-run the migration now, it should succeed or it should give you a different view that is giving you problems. Rinse and repeat until the migration succeeds.

**Comment by leweafan** [comment]
Thanks!
