### ISSUE TITLE
Materialized View "view name" has not been populated

### ISSUE THREAD

**Issue by jun1st** [thoughtbot/scenic#184]
I encountered following error when running my rspec tests on CircleCI.

`Materialized View "view name" has not been populated`

The view creating script exists in schema.rb. But when running this view related tests,  this error occurs.

any ideas?

**Comment by devonestes** [comment]
So in the SQL dump for your `structure.sql` or `schema.rb` file, you'll see at the end of materialized view definitions either `WITH NO DATA` or `WITH DATA`. Right now I bet you have `WITH NO DATA` in there, which is why it isn't populating. If you remove the `NO`, then all should be good!

I do a search and replace in vim to correct this - you could probably do the same in whichever editor you're using.

**Comment by jun1st** [comment]
Thanks @devonestes, this fixes the test.

Instead of fix the SQL dump file manually, is there any other alternative to make rails generate the file with "WITH DATA"?

**Comment by devonestes** [comment]
The rake task in Rails that generates that SQL file (for Postgres) just shells out to the `pg_dump` command, so you'd have to find a setting in that command that changes that output. I did a quick look at the docs and couldn't find anything...

Alternatively, you could automate that search and replace. I've done through a macro, but you could through an after-commit hook, or a custom rake task to generate the schema dump.

Also, I think this issue can be closed since it isn't actually an issue with Scenic 😄

**Comment by jun1st** [comment]
Thanks for the quick response and help 💯

**Comment by zyqxd** [comment]
For those who stumble across this from their google search:

An alternative to this problem is to execute `REFRESH MATERIALIZED VIEW <view_name>`, which would mark the table as scannable again.

For me, it was adding an `ActiveRecord::Base.connection.execute` in my `spec_helper.rb`

**Comment by johnmosesman** [comment]
Had the same issue and I did the refreshes in the `before(:suite)` hook in my `spec_helper` and it works.

This feels more like a hack than fixing the actual issue. My new code wasn't calling either of these views. It was just doing a `ActiveRecord::Base.connection.execute(some_sql_query)`.

```
# spec/spec_helper.rb
RSpec.configure do |config|
  ...

  config.before(:suite) do
    ActiveRecord::Base.connection.execute("REFRESH MATERIALIZED VIEW public.view_1;")
    ActiveRecord::Base.connection.execute("REFRESH MATERIALIZED VIEW public.view_2;")
  end
end
```

(Remember to include your view's namespace like `public` if you're using a `structure.sql` as it silently fails without it.)

My main question is what does this have to do with the scenic gem? Seems like it has more to do with rspec than scenic but this is the only relevant google result that comes up for this.

**Comment by jarl-dk** [comment]
@devonestes : I suggest you add a description of the workaround mentioned in https://github.com/scenic-views/scenic/issues/184#issuecomment-567563584 in the README.md file.

**Comment by afromankenobi** [comment]
@johnmosesman i did a little improve to fetch automatically all views:

``` ruby
  config.before(:suite) do
    # Get the names of all materialized views
    # then update them all
    views = ActiveRecord::Base.connection.execute <<-SQL
      SELECT oid::regclass::text
      FROM   pg_class
      WHERE  relkind = 'm';
    SQL

    views.each do |view|
      view_name = view['oid']
      view_class_name = view_name.singularize.camelize.constantize
      query = <<-SQL
        REFRESH MATERIALIZED VIEW #{ "CONCURRENTLY" if view_class_name.count.positive? } #{view_name};
      SQL
      ActiveRecord::Base.connection.execute query
    end
  end

```
