### ISSUE TITLE
Inconsistent dumping of arrays of text in SQL queries in views

### ISSUE THREAD

**Issue by Dorian** [thoughtbot/scenic#195]
I keep getting this diff in my `db/schema.rb`:

```diff
-            WHERE ((t.type)::text = ANY (ARRAY[('A'::character varying)::text, ('B'::character varying)::text]))) ct ON ((ct.b_id = b.id)))
+            WHERE ((t.type)::text = ANY ((ARRAY['A'::character varying, 'B'::character varying])::text[]))) ct ON ((ct.b_id = b.id)))
```

From this SQL:

```
        WHERE t.type in ('A', 'B')) ct ON ct. b_id = b.id
```

**Comment by derekprior** [comment]
Are you working with a team? Are you all on the same Postgres version?

**Comment by Dorian** [comment]
I'm on `postgres (PostgreSQL) 9.6.1`. The one on Heroku is `9.4.10`. I'm gonna ask my coworker later.

**Comment by Dorian** [comment]
But shouldn't this be normalized across postgres versions?

**Comment by calebthompson** [comment]
@Dorian 

> "shouldn't"

probably, but in practice it probably isn't. Did you hear from your coworker?

**Comment by derekprior** [comment]
We don't have a good way of normalizing the output from Postgres versions. One thing we have considered in the past is tracking views and their current version in a metadata table we would maintain. Then, instead of dumping the actual SQL of your view, we could dump: `create_view :searches, version: 3` or similar.

This would have a couple of downsides:

1. There'd no longer be a single file you could review to see a diff of the view definition in a PR. While the view definitions we pull from Postgres aren't the most readable SQL, they're often enough to see major differences. This is complicated if users on the team have differing Postgres versions.

2. We wouldn't be able to dump views created with anything other than scenic. Right now the schema dumper will handle views you created manually or with a previous gem. That wouldn't be the case if we moved to a metadata table.

@calebthompson What do you think?

**Comment by calebthompson** [comment]
I'm :-1: on storing views in metadata. Too much magic and it's going to cost us later I fear. The underlying issue here is array ordering- does Postgres guarantee that? If so, how are these arrays being dumped in different orders?

Seeing an example would help us make sure this doesn't happen any more.

**Comment by Dorian** [comment]
@calebthompson he uses 9.6.1 too

**Comment by derekprior** [comment]
I don't think it's a bug in postgres - I think it's a difference in how the two versions of postgres dump the schema. I think using the same version of postgres locally and on heroku will resolve this.
