### ISSUE TITLE
Version conflicts

### ISSUE THREAD

**Issue by jalada** [thoughtbot/scenic#213]
We love Scenic but when we're working on separate features that involve modifying the same SQL view, we hate resolving the merge conflicts that come with having two different forked versions with the same version number.

Do you have any suggestions for us? Is there a way versioning could be improved in Scenic? How come you don't adopt a similar timestamp-style versioning as Rails?

**Comment by derekprior** [comment]
Do you mean you have multiple developers (or perhaps one developer in multiple branches) working on new versions of the same view? The merge conflict is a feature here. 

With standard table migrations, we can both write migrations that target the same table without issue because SQL has a nice DSL (used by Rails' own DSL) for adding, removing, and altering single columns on a table. In one branch, I can `add_column :users, :email, :text` and you can `add_column :users, :admin, :boolean` in another branch and when we both merge and run migrations things will work just fine. The `users` table will end up with `email` and `admin` columns, regardless of the order those migrations end up being run in. So long as the two migrations don't target the same column or in some other way conflict, the order tends not to matter when it comes to features merged around the same time.

SQL doesn't offer this same level of granularity for views. When altering a view you redefine the entire thing every time. Let's consider a theoretical `search_results` view. If I generate a new version of the `search_results` view in my branch and add a `UNION` to pull in search results from `posts` and you do the same in your branch for `comments`, those definitions will conflict. If we used timestamped file names, you wouldn't be alerted to this conflict and whichever migration that ran last would "win". 

By using integer-versioned view definition files, we accomplish two things:

1. We avoid this problem. You will get a merge conflict. Whomever merged last will have to resolve the merge conflict, and bump their view version number.
2. We make the actual migrations much simpler to write and reason about. `update_view :search_results, version: 3` is much simpler to write, edit, and read than `update_view :search_results, version: 20170711211015`, for example.  It's much simpler to find and open the corresponding view definition file with the integer version.
