### ISSUE TITLE
refresh_materialized_view when cascade: true

### ISSUE THREAD

**Issue by jamesstonehill** [thoughtbot/scenic#230]
When I try to `Scenic.database.refresh_materialized_view(table_name, concurrently: true, cascade: true)` I get the error `bad value for range`. 

![screen shot 2018-01-15 at 09 54 57](https://user-images.githubusercontent.com/19637233/34936750-7a032bee-f9da-11e7-8c20-b7b79458c697.png)

but when I set `cascade: false` it succeeds. Not sure what's going on here. If I have some kind of configuration error, is there a way to make this more apparent with the error?

I'm running psql version 9.6.5

**Comment by devonestes** [comment]
@jamesstonehill Looks like the error is in determining the order of dependencies that need to be refreshed. If it's possible, can you share an overview of the dependencies for the materialized view that you're trying to cascade the refresh? For example, something like this:

```
A -> B
A -> C
B -> C
C -> D
```

And just so we're clear, when I say "dependencies", I'm talking about other materialized views that this materialized view selects from.

That'll be a huge help in figuring out what's going on - thanks!

**Comment by jamesstonehill** [comment]
Hi @devonestes. I appreciate the quick response. This view actually doesn't depend on any other views. It just depends on a few regular tables. Maybe this is where I'm going wrong?

I plan on having this table be the parent to a number of other materialized views and I wasn't sure from the documentation if I needed to set `cascade: true` on the parent view or the child view. I will be 'manually' triggering refreshes for this table from a cron job.

**Comment by devonestes** [comment]
@jamesstonehill Cool, yeah, that's probably the problem, although I'd have to poke around to be sure. We should totally give a more helpful error if that is indeed the case, though!

`cascade: true` should be used if your materialized view selects from other materialized views. In those cases, we "cascade" the refresh down to the bottom of the dependency tree to ensure you're getting the most up-to-date data possible. So, in the example below:

```
A -> B
A -> C
B -> C
C -> D
```

If we did `Scenic.database.refresh_materialized_view("A", concurrently: true, cascade: true)`, we would first refresh D, then C, then B, then finally A. If your materialized view doesn't depend on any other materialized views, then you don't need `cascade: true` since you'll have nothing that needs refreshing.

**Comment by calebthompson** [comment]
#231 was merged, and should fix this (thanks to @devonestes). @jamesstonehill can you try using the master branch on GitHub and let us know if it works for you?

```
gem "scenic", github: "thoughtbot/scenic"
```

**Comment by jamesstonehill** [comment]
Yeah, tests are passing against master and failing against the latest rubygems release, so I can confirm that this change fixes the issue. Although, I ended up just using the `cascade` option correctly in the first place tbh. 😄
