### ISSUE TITLE
Adding default value to column used in migration results in Error for changing type.

### ISSUE THREAD

**Issue by RachelScodes** [thoughtbot/scenic#239]
Ruby version: 2.4.0
Rails version: 5.1.4
Scenic Version: 1.4.1

Scenario:

1. Create table - `:items` with column `t.integer :amount`
2. create `my_view` that uses `items.amount`
3. create migration to update items:
`change_column :items, :amount, :integer, default: 1, null: false`
4. run rake db:migrate

See error in console:
```
PG::FeatureNotSupported: ERROR:  cannot alter type of a column used by a view or rule
DETAIL:  rule _RETURN on view my_view depends on column "amount"
```

My confusion comes from two things: 
1 - I'm not changing the type of the column, and 
2 - isn't this abstracted away by scenic? 

To get around this I have to DROP and then RECREATE `my_view` to add the default value to `items.amount.` Is this a bug or feature of scenic?

**Comment by RachelScodes** [comment]
if anyone else comes across this issue and is using a materialized view which cannot be dropped with the same syntax: using `change_column_default :table, :column, <new_default_value>` worked without touching views at all.

I am leaving this issue open since the change_column _should_ work if the type is the same, and even if it isn't, it seems like an issue using scenic in rails 5.

**Comment by kofronpi** [comment]
+1

**Comment by derekprior** [comment]
> My confusion comes from two things:
> 1 - I'm not changing the type of the column, and

I can only assume that adding the `null: false` to the column definition changes it's type because now that corresponding column in the view is also `null: false`.

> 2 - isn't this abstracted away by scenic?

No. Scenic does not inject itself into schema statements such as `change_column`, `change_table`, etc. I expect that it *could* and then perform any number of queries to see if views wwere going to be inmpacted, but I think it's out of scope for what I have in mind as the job of the library.

> To get around this I have to DROP and then RECREATE my_view to add the default value to items.amount. Is this a bug or feature of scenic?

I don't see this as a scenic bug.
