### ISSUE TITLE
Solutions to file clutter after many revisions?

### ISSUE THREAD

**Issue by fgblomqvist** [thoughtbot/scenic#243]
When I first learned about Scenic it seemed awesome in every way possible. Now, after having used it on a major project for a few months I realize that it's turning into a mess with 10+ revisions for certain views and old dropped views laying around with all their revisions. And this is only after months, I can't imagine what things will look like after a year or two.

I still think Scenic is great in a lot of ways, but unless I'm missing something, it could use a better way of handling old revisions.

This is my idea:
Add a mode that just utilizes version control (=git). Keep only one file for each view, and allow the users to generate a migration for that view through a scenic command. That command generates the migration file, grabs the last committed revision of the view-file and puts in the `down`, and then puts whatever is currently in the view-file in `up` (using execute statements).

My idea is probably missing a necessary check/feature or two, but as a concept, I think it would lead to a less cluttered workspace and a more normalized model (e.g. if someone wants to check out old versions, use version control or check the migrations directly).

A less aggressive approach could be to add an archive command to scenic, that essentially edits all the old migrations and replaces the scenic statements (e.g. create_view, replace_view, etc.) with their respective SQL code, including the relevant revision of the view. Then it safely deletes all the old revision-files that it "archived". Sure, going back and editing migrations might not be great, but it's all opinion-based.

Would love to hear some input/responses to these 2 different ideas :)

**Comment by derekprior** [comment]
Hi @fgblomqvist, I'm glad you're enjoying (sort of) Scenic. The decision to retain all old versions of the views is in keeping with the practice of keeping old migrations. Our view is that migrations in your project should be runnable at any given point. If we remove old `.sql` files then this will no longer be the case.

If you'd prefer instead to truncate migrations then you are also free to truncate old versions of the views. I'm not sure the generators would behave as expected in this scenario (since they'd detect a missing `_v01.sql` file) but that could be addressed.

From what you're describing, it sounds like you're most interested in Scenic's ability to modify views in migrations and, perhaps, to dump the resulting SQL to `db/schema.rb`. If this is the case, you may with to check out [`schema_plus_views`](https://github.com/SchemaPlus/schema_plus_views) as this may be closer to your expectation there.

I'm not particularly swayed by clutter argument. I have very little reason to interact with the files in `db/views` -- about as much reason as you have to interact with the files in `db/migrate`.

**Comment by fgblomqvist** [comment]
Thanks for your thorough response. I understand your point of view. I will try the truncating at some point and come back here if it didn't work.
